"""Add DAO table

Revision ID: 0a24e7582ccf
Revises: 1a31ce608336
Create Date: 2025-10-25 04:57:07.380353

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0a24e7582ccf'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dao',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('contract_address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('chain', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'INDEXING', 'COMPLETED', 'FAILED', name='daostatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dao_contract_address'), 'dao', ['contract_address'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dao_contract_address'), table_name='dao')
    op.drop_table('dao')
    # ### end Alembic commands ###
