"""Add detailed fields to DAO model

Revision ID: 6a23ff305046
Revises: f05b52753389
Create Date: 2025-10-25 13:38:00.181075

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a23ff305046'
down_revision = 'f05b52753389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dao', sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('dao', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('dao', sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('dao', sa.Column('proposal_threshold', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('dao', sa.Column('votable_supply', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('dao', sa.Column('funding_quorum', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('dao', sa.Column('constitutional_quorum', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('dao', sa.Column('delegated_power', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('dao', sa.Column('proposal_delay', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('dao', sa.Column('voting_period', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('dao', sa.Column('token_address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('dao', sa.Column('timelock_address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dao', 'timelock_address')
    op.drop_column('dao', 'token_address')
    op.drop_column('dao', 'voting_period')
    op.drop_column('dao', 'proposal_delay')
    op.drop_column('dao', 'delegated_power')
    op.drop_column('dao', 'constitutional_quorum')
    op.drop_column('dao', 'funding_quorum')
    op.drop_column('dao', 'votable_supply')
    op.drop_column('dao', 'proposal_threshold')
    op.drop_column('dao', 'social_links')
    op.drop_column('dao', 'description')
    op.drop_column('dao', 'logo_url')
    # ### end Alembic commands ###
