"""Add DAOVote model

Revision ID: f05b52753389
Revises: 0a24e7582ccf
Create Date: 2025-10-25 05:34:38.162285

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f05b52753389'
down_revision = '0a24e7582ccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daovote',
    sa.Column('voter_address', sqlmodel.sql.sqltypes.AutoString(length=42), nullable=False),
    sa.Column('proposal_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('support', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dao_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['dao_id'], ['dao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daovote')
    # ### end Alembic commands ###
